// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddIngredient(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddIngredient'](arg1, arg2, arg3);
}

export function GetIngredients() {
  return window['go']['main']['App']['GetIngredients']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
