// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddIngredient(arg1:string,arg2:number,arg3:string):Promise<void>;

export function GetIngredients():Promise<Array<models.Ingredient>>;

export function Greet(arg1:string):Promise<string>;
